name: Fix and Lint HTML

on: push

jobs:
  lint-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install HTML Linter
      run: |
        sudo apt-get update
        sudo apt-get install -y tidy

    - name: Lint and Fix HTML
      run: find . -name "*.html" -exec tidy -quiet -modify -indent -wrap 250 {} \;

    - name: Check for changes
      run: git diff --exit-code || echo "Changes detected"

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
