name: ShellCheck Analysis and Auto Commit

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: find . -type f \( -name "*.sh" -o -name "*.bash" \) -exec shellcheck {} \;

      - name: Install shfmt
        run: sudo apt-get install -y shfmt

      - name: Format shell scripts
        run: find . -type f \( -name "*.sh" -o -name "*.bash" \) -exec shfmt -w -i 4 -ci -sr {} \;

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-format shell scripts"
